export const RECEIVE_CURRENT_USER = "RECEIVE_CURRENT_USER";
export const LOGOUT_CURRENT_USER = "LOGOUT_CURRENT_USER";

export const RECEIVE_ERRORS = "RECEIVE_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const PURCHASE_STOCK = "PURCHASE_STOCK";

export const LOAD_USER_STOCK_INFO = "LOAD_USER_STOCK_INFO";

export const SWITCH_LOADING = "SWITCH_LOADING";