export const RECEIVE_CURRENT_USER = "RECEIVE_CURRENT_USER";
export const LOGOUT_CURRENT_USER = "LOGOUT_CURRENT_USER";

export const PURCHASE_STOCK = "PURCHASE_STOCK";

export const LOAD_USER_STOCK_INFO = "LOAD_USER_STOCK_INFO";

